### ISSUE TITLE
Pretrained adversarial model has low accuracy

### ISSUE THREAD

**Issue by wielandbrendel** [P2333/Mixup-Inference#1]
Thanks for making all the code and pretrained models available. That's great! The pretrained weights for the mixup model seem to work, I get 84% accuracy as reported in your paper. The adversarially trained model, however, has only 43% accuracy on clean samples. Are you sure you uploaded the right checkpoint?

**Comment by P2333** [comment]
Thank you for pointing out!
I check and upload the correct checkpoint for IAT. Please re-download it.

**Comment by wielandbrendel** [comment]
Great, thanks for the quick reply! The clean accuracy is 89.6%, but the mixup mechanism reduces accuracy to 73.6%. That's different from the mixup weights which have 94% accuracy and 84.3% with the mixup mechanism. So there is still something odd with the IAT weights, but only for IAT + MI-OL. Do you have any ideas why that might happen?

**Comment by P2333** [comment]
Yes, that's because the default --lambda=0.5 in the running command. This is the setting for mixup-trained models, while for IAT-trained models we set --lambda=0.6. For detailed parameters setting, please refer to Table 4 and Table 5 in the appendix of our paper. Sorry for the inconvenience.

**Comment by wielandbrendel** [comment]
Ah, great - now everything fits. Thanks for the (super fast) clarifications!
